### ISSUE TITLE
removed from CRAN; WebTechnology Task View

### ISSUE THREAD

**Issue by wibeasley** [cpsievert/XML2R#10]
@cpsievert, I'm a maintainer of the [WebTechnology Task View](https://cran.r-project.org/web/views/WebTechnologies.html).  It looks like [your package was recently removed from CRAN](https://github.com/cran-task-views/WebTechnologies/issues/528).  

1. Do you have any plans to resubmit it?
2. If we remove it from the Task View, is there another package you'd like to see replace it (on the Task View description).

**Comment by cpsievert** [comment]
On CRAN now
